# Generated by Django 2.0.2 on 2018-03-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0003_auto_20180301_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
