# Generated by Django 2.0.3 on 2018-03-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0005_auto_20180305_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentID',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='className',
            field=models.CharField(max_length=64),
        ),
    ]
