# Generated by Django 2.0.2 on 2018-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0005_auto_20180305_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='Discher', max_length=128),
            preserve_default=False,
        ),
    ]
