# Generated by Django 2.0.1 on 2018-03-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0006_remove_fields'),
        ('pollingSite', '0006_student_lastname'),
    ]

    operations = [
    ]
