# Generated by Django 2.0.3 on 2018-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0007_merge_20180311_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
