# Generated by Django 2.0.3 on 2018-03-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0008_auto_20180311_1433'),
        ('pollingSite', '0007_merge_20180311_1424'),
    ]

    operations = [
    ]
