# Generated by Django 2.0.3 on 2018-03-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0009_merge_20180313_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
    ]
