# Generated by Django 2.0.3 on 2018-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0010_remove_poll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
